services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://theoretically-lamentable-wiley.ngrok-free.dev
      - N8N_PUBLIC_API_DISABLED=false
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./data:/home/node/.n8n
      - ./Workflows:/data/import:ro
    networks:
      - ia-net

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyzer
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
    networks:
      - ia-net

networks:
  ia-net:
    driver: bridge
